# Generated by Django 2.2.6 on 2019-12-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venuename', models.TextField()),
                ('location', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('handicap', models.TextField()),
                ('wifi', models.TextField()),
                ('coatcheck', models.TextField()),
                ('food', models.TextField()),
                ('parkinggarage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.TextField()),
                ('date', models.DateTimeField()),
                ('website', models.URLField(blank=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Venue')),
            ],
        ),
    ]
