# Generated by Django 2.2.6 on 2019-12-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='streetname',
            field=models.TextField(default='here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='zipcode',
            field=models.TextField(blank=True),
        ),
    ]
