# Generated by Django 2.2.6 on 2019-12-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191202_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.TextField(default='State'),
            preserve_default=False,
        ),
    ]
