# Generated by Django 2.2.6 on 2019-12-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20191209_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
    ]
