# Generated by Django 2.2.6 on 2019-12-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_venue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance', models.TextField()),
                ('description', models.TextField()),
                ('video', models.URLField()),
            ],
        ),
    ]
