# Generated by Django 2.2.6 on 2019-11-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('city', models.TextField()),
                ('email', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
