# Generated by Django 2.2.6 on 2019-11-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_statusmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusmessage',
            old_name='person',
            new_name='profile',
        ),
    ]
