# Generated by Django 2.2.6 on 2019-11-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0003_auto_20191112_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_fb.Profile'),
        ),
    ]
