# Generated by Django 2.2.6 on 2019-11-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_statusmessage_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusmessage',
            old_name='image_file',
            new_name='image',
        ),
    ]
