# Generated by Django 2.2.6 on 2019-11-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20191111_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='person',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='quotes.Person'),
            preserve_default=False,
        ),
    ]
